import { SVG_ICONS } from "./svgIcons";

export const preSelectedTheme = "codeVibes";
export const settingsData = [
  {
    type: "theme",
    title: "Game Themes",
    iconPath: "palette.svg",
    radioName: "game-theme",
    items: [
      {
        id: "codeVibes",
        label: "Code vibes theme",
      },

      {
        id: "gaming",
        label: "Gaming theme",
      },

      {
        id: "daProjects",
        label: "DA Projects theme",
      },

      {
        id: "food",
        label: "Food theme",
      },
    ],
  },

  {
    type: "player",
    title: "Choose player",
    iconPath: "player.svg",
    radioName: "player",
    items: [
      {
        id: "blue",
        label: "Blue",
      },
      {
        id: "orange",
        label: "Orange",
      },
    ],
  },

  {
    type: "size",
    title: "Board size",
    iconPath: "board_size.svg",
    radioName: "board-size",
    items: [
      {
        id: "16",
        label: "16 cards",
      },
      {
        id: "24",
        label: "24 cards",
      },
      {
        id: "36",
        label: "36 cards",
      },
    ],
  },
];

export const themes = {
  codeVibes: {
    id: "code",
    label: "Code vibes theme",
    bodyClass: "theme-code",
    headerClass: "header-code",
    scoreWrapperClass: "score-wrapper-code",
    exitBtnClass: "exit-btn-code",
    gameBackground: "game-bg-code",
    cardStyle: "card-style-code",
    gameOverBackground: "game-over-bg-code",
    gameOverTextClass: "game-over-text-code",
    winnerBackground: "winner-bg-code",
    drawTextClass: "draw-text-code",
    drawClass: "draw-code",
    backBtnText: "Back to start",
    backBtnClass: "back-btn-code",
    backBtnGameOverClass: "back-btn-game-over-code",
    cardBackground: "card-bg-code",
    cardMatchBorder: "card-match-border-code",
    cardMatchBackground: "card-match-bg-code",
    cardMatchShadow: "card-match-shadow-code",
    playerIcon: "player-code.svg",
    previewPath: "preview-code.svg",
    exitModalClass: "exit-modal-code",
    exitTextClass: "exit-text-code",
    exitCancelBtn: "Back to game",
    exitConfirmBtn: "Exit game",
    exitCancelBtnClass: "exit-cancel-btn-code",
    exitConfirmBtnClass: "exit-confirm-btn-code",

    motifs: [
      "angular.svg",
      "bootstrap.svg",
      "css.svg",
      "database.svg",
      "django.svg",
      "firebase.svg",
      "git.svg",
      "github.svg",
      "html.svg",
      "javascript.svg",
      "node-js.svg",
      "python.svg",
      "react.svg",
      "sass.svg",
      "terminal.svg",
      "typescript.svg",
      "vscode.svg",
      "vue-js.svg",
    ],

    winnerIcons: {
      winBlue: "win_blue.svg",
      winOrange: "win_orange.svg",
      draw: "scales.svg",
      decoration: "confetti.svg",
    },
  },

  gaming: {
    id: "gaming",
    label: "Gaming theme",
    bodyClass: "theme-gaming",
    headerClass: "header-gaming",
    scoreWrapperClass: "score-wrapper-gaming",

    exitBtnClass: "exit-btn-gaming",
    gameBackground: "game-bg-gaming",
    cardStyle: "card-style-gaming",
    gameOverBackground: "game-over-bg-gaming",
    gameOverTextClass: "game-over-text-gaming",
    winnerBackground: "winner-bg-gaming",
    drawTextClass: "draw-text-gaming",
    drawClass: "draw-gaming",
    backBtnText: "Home",
    backBtnClass: "back-btn-gaming",
    backBtnGameOverClass: "back-btn-game-over-gaming",
    cardBackground: "card-bg-gaming",
    cardMatchBorder: "card-match-border-gaming",
    cardMatchBackground: "card-match-bg-gaming",
    cardMatchShadow: "card-match-shadow-gaming",
    playerIcon: "player.svg",
    previewPath: "preview-gaming.svg",
    exitModalClass: "exit-modal-gaming",
    exitTextClass: "exit-text-gaming",
    exitCancelBtn: "No, back to game",
    exitConfirmBtn: "Yes, quit game",
    exitCancelBtnClass: "exit-cancel-btn-gaming",
    exitConfirmBtnClass: "exit-confirm-btn-gaming",

    motifs: [
      "banana.svg",
      "card.svg",
      "coin.svg",
      "controller.svg",
      "dice.svg",
      "gameboy.svg",
      "labyrinth.svg",
      "medal.svg",
      "meeple_circle.svg",
      "meeple_square.svg",
      "meeple_triangle.svg",
      "mushroom.svg",
      "pacman_game.svg",
      "pacman.svg",
      "pixel.svg",
      "play.svg",
      "puzzle.svg",
      "snake.svg",
    ],
    winnerIcons: {
      winBlue: "goblet.svg",
      winOrange: "goblet.svg",
      draw: "scales.svg",
      decoration: "",
    },
  },

  daProjects: {
    id: "daProjects",
    label: "DA Projects theme",
    bodyClass: "theme-projects",
    headerClass: "header-projects",
    scoreWrapperClass: "score-wrapper-projects",
    exitBtnClass: "exit-btn-projects",
    gameBackground: "game-bg-projects",
    cardStyle: "card-style-projects",
    gameOverBackground: "game-over-bg-projects",
    gameOverTextClass: "game-over-text-projects",
    winnerBackground: "winner-bg-projects",
    drawTextClass: "draw-text-projects",
    drawClass: "draw-projects",
    backBtnText: "Home",
    backBtnClass: "back-btn-projects",
    backBtnGameOverClass: "back-btn-game-over-projects",
    cardBackground: "card-bg-projects",
    cardMatchBorder: "card-match-border-projects",
    cardMatchBackground: "card-match-bg-projects",
    cardMatchShadow: "",
    playerIcon: "player.svg",
    previewPath: "preview-projects.svg",
    exitModalClass: "exit-modal-projects",
    exitTextClass: "exit-text-projects",
    exitCancelBtn: "Back to game",
    exitConfirmBtn: "Exit game",
    exitCancelBtnClass: "exit-cancel-btn-projects",
    exitConfirmBtnClass: "exit-confirm-btn-projects",

    motifs: [
      "noodles.svg",
      "soup.svg",
      "eggs.svg",
      "flower.svg",
      "join.svg",
      "chefs_hat.svg",
      "coderr.svg",
      "basket.svg",
      "pokeball.svg",
      "connect4.svg",
      "smile.svg",
      "blue.svg",
      "daBubble.svg",
      "polloLoco.svg",
      "cuisine.svg",
      "person.svg",
      "shark.svg",
      "coins.svg",
    ],

    winnerIcons: {
      winBlue: "win_blue.svg",
      winOrange: "win_orange.svg",
      draw: "scales.svg",
      decoration: "confetti.svg",
    },
  },

  food: {
    id: "food",
    label: "Food theme",
    bodyClass: "theme-food",
    headerClass: "header-food",
    scoreWrapperClass: "score-wrapper-food",
    exitBtnClass: "exit-btn-food",
    gameBackground: "game-bg-food",
    cardStyle: "card-style-food",
    gameOverBackground: "game-over-bg-food",
    gameOverTextClass: "game-over-text-food",
    winnerBackground: "winner-bg-food",
    drawTextClass: "draw-text-food",
    drawClass: "draw-food",
    backBtnText: "Home",
    backBtnClass: "back-btn-food",
    backBtnGameOverClass: "back-btn-game-over-food",
    cardBackground: "card-bg-food",
    cardMatchBorder: "card-match-border-food",
    cardMatchBackground: "card-match-bg-food",
    cardMatchShadow: "",
    playerIcon: "player.svg",
    previewPath: "preview-food.svg",
    exitModalClass: "exit-modal-food",
    exitTextClass: "exit-text-food",
    exitCancelBtn: "No, back to game",
    exitConfirmBtn: "Exit game",
    exitCancelBtnClass: "exit-cancel-btn-food",
    exitConfirmBtnClass: "exit-confirm-btn-food",

    motifs: [
      "pommes.svg",
      "pizza.svg",
      "sandwich.svg",
      "donut.svg",
      "sushi.svg",
      "corndog.svg",
      "cheeseburger.svg",
      "pretzel.svg",
      "cupcake.svg",
      "pudding.svg",
      "pannacotta.svg",
      "chocolate.svg",
      "chickenwings.svg",
      "wrap.svg",
      "pita.svg",
      "icecream.svg",
      "salad.svg",
      "macarons.svg",
    ],

    winnerIcons: {
      winBlue: "win_blue.svg",
      winOrange: "win_orange.svg",
      draw: "scales.svg",
      decoration: "",
    },
  },
};